---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sure-pg
  namespace: services
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: postgres-oci
    namespace: flux-system
  values:
    image:
      registry: docker.io
      repository: postgres
      tag: "18.3"

    customUser:
      name: sure

    persistence:
      storageClass: local-path
      size: 5Gi
      annotations:
        k8up.io/backup: "false"
