apiVersion: v1
stringData:
  adminUser: ENC[AES256_GCM,data:GaEjx2tJt6IWSXfY,iv:jKbSY9QXkG05DRlf4QDGestyGLWdWMbaVNjqXiH4Xo4=,tag:Wfn0IY6Hk/JK4Xp/qONg4Q==,type:str]
  adminPass: ENC[AES256_GCM,data:0p+8HcVk+F+KYbFZWZXEOdSuU4gDyyWBoF1Hv8uiEEE=,iv:R/efPiDjf7HSQOaagN8aNrs/l/SGnXv6hejuWJdIZUg=,tag:pK7gOhLDSAX8RZtO6Dz/GQ==,type:str]
  providerClientId: ENC[AES256_GCM,data:T0aF2gIJB69nFi28DRiiS6dqIic8DHREcKnwPOKSWJATKpWV,iv:ADSeWsUl6ozj4OYh4g2SQlscjqxuDtzwDO3cm+4/afQ=,tag:bD5oUkwWrvD3LhSvptEtaw==,type:str]
  providerClientSecret: ENC[AES256_GCM,data:TvQteD/knWvT8TPCuWP5tzH2B3A8Ym3CCvA8MYrr6vQ=,iv:dvFzRHlkKSUq7kE0DwrLOa6OVH3WAlxKDuvTlmkIJCQ=,tag:YY4HHx9IOel1C4D5fbNDKg==,type:str]
kind: Secret
metadata:
  name: grafana-creds
  namespace: supervision
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnV0haUHB3aEtLNDc5ZG01
        VHZHNStJNSsvZzBFc2tlTmkwVGkyZWZ1ZVRFCkNDdkNweGFTWHFxRk54aXlXdGpO
        dExRK3B2QTJVUzVZNnQ1V3I2ZTg3dEEKLS0tIDlxZmc4bFJCNHhBMzA4OFNZSDh2
        c0ZybVV2c0pXTythZGpSejdmZkFaQXcKwYioPg+A/bVzClCWb8yNE5p6/SZkK7Y+
        a10mX9lH02T8gCqWrwdX/92+oKUQP+5bjRE2GYlDp/zaJyIzRHcy0Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  lastmodified: "2026-06-08T15:53:52Z"
  mac: ENC[AES256_GCM,data:sH/jsLDW5slAldxLsQFHV66MpJoXS5zpF0Ss02hOkuqwfahfZVi4DXJ7HtDzgK5+OK5gD+RGjm7IAakrCaJVLu2PlHIkrs+NSCNzPud57Gp0aiTd7mVcLnUVI9Kk7oPMBgj09ERHSaNIZpS6EJPG3iB5BuKRhRbX+n57a4Q1UYc=,iv:3TOcAgzK+FWQsdBEF4FYN+exU5jfrcMmaVEmPSZ2L6Y=,tag:myUN0BGEClA8TEhUj493rw==,type:str]
  version: 3.13.1
