apiVersion: v1
stringData:
  JWT_SECRET: ENC[AES256_GCM,data:kdUJiUuvLEef+OuDfujnmhxGwysky6YsvzCWAiBodl/XINWnYdRqeYR10Ps=,iv:TH6zdzYXQLQVqFxsZO6w4utOcGkbyfxBRMQIFiExq3I=,tag:vKFT6Acui69HcvYi1mXQQQ==,type:str]
  KITE_ENCRYPT_KEY: ENC[AES256_GCM,data:nDLzSMcjo1mFyRTFaEuzouhLMHxo/4LPExN8VtZxSAjBQ4g0N0roe93AlEs=,iv:2J7Qo3kF56FJOqTUoCwyQCrqoT/qbJE6OyY7BxJcjVY=,tag:6vN3DYtVKAaR4sNN7cuYpA==,type:str]
  DB_TYPE: ENC[AES256_GCM,data:rueVl7Os,iv:BSstwRD55BWEZTrMyML+nnsSnbF4Nmzn98CWY4EA5bo=,tag:Y6q/ViSjweUaVAgZZUAVxA==,type:str]
kind: Secret
metadata:
  name: kite-secret
  namespace: supervision
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaT2NvNkx1MDRUalgrZ05w
        ejAvNFdmSEtMOElUN2VZRlYxVE44S0xWY3cwCi9jdmozeDJsVUNHY2c4ZU4vb09H
        K3RNY3pFTitZcElaMFlhYlFPV1RkbWsKLS0tIGlpR2NwbEJYc2Q2OWs4WFpscjdP
        S0hRZ2FsUVpZNnhFUDZ3Zm9VT2dTR1EK1jc0+t34Q8xtJaLKJcqD2VeZsQM8/8zu
        7mObbAEo0n4Rlu7GhNxAdCZ4hSah293GXtjvEyJy+/elFP3kRf9n3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-25T18:54:47Z"
  mac: ENC[AES256_GCM,data:FdKpc9nw2fOrEP8cyAJ4HBMwu3sIMKCtrBEn51EPNg+77WGRydxnJwmUOkgmNJaSlBqfwdHpwZOkm3dORrxIhZFl/s6ZsujzeqoaMYZrvV3w/mW2XRsN3PtXb1n5A92gZx4TDqVNQKzpb0feCcvwe0XyCDlWSxlXlhWkZjZGRIo=,iv:lGyU+noGTa1fr22FWqabEGuh4LYIDt0CEmfk8mELqn8=,tag:/xiW0xNhz+CXiHphgnokkA==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.12.2
