---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: garage-qui-backup-store
  namespace: media
spec:
  configuration:
    destinationPath: s3://qui-backup/pgsql/
    endpointURL: https://ohara.infrao.top:3900
    s3Credentials:
      accessKeyId:
        name: garage-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: garage-creds
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: qui-backup
spec:
  schedule: "0 30 4 * * *"
  cluster:
    name: qui-database
  immediate: true
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: qui-database
  annotations:
    k8up.io/backup: "false"
spec:
  instances: 1

  storage:
    storageClass: local-path
    size: 1Gi

  imageName: ghcr.io/cloudnative-pg/postgresql:16.13

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: garage-qui-backup-store
