---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qui
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k8s/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: qui
        image: ghcr.io/autobrr/qui:v1.16.1
        # volumeMounts:
        #   - mountPath: /config
        #     name: config
        #   - mountPath: /media-root
        #     name: arr-media-root
        env:
          - name: QUI__AUTH_DISABLED
            value: "true"
          - name: QUI__I_ACKNOWLEDGE_THIS_IS_A_BAD_IDEA
            value: "true"
          - name: QUI__CHECK_FOR_UPDATES
            value: "false"
          # - name: QUI__CORS_ALLOWED_ORIGINS
          #   value: ""
          - name: QUI__DATABASE_ENGINE
            value: "postgres"
          - name: QUI__DATABASE_DSN
            valueFrom: 
              secretKeyRef: 
                name: "qui-database-app"
                key: uri
          - name: QUI__DATA_DIR
            value: "1000"
          - name: TZ
            value: Europe/Paris
        envFrom:
          - secretRef: 
              name: qui-creds
        # volumes:
          # - name: arr-media-root
          #   persistentVolumeClaim:
          #     claimName: arr-media-root
          # - name: config
          #   persistentVolumeClaim:
          #     claimName: deluge-config
        service: 7476
        ingress:
          domain: qui.egghead.infrao.top
          # oidc:
          #   BypassKey: false
          #   secretRef: deluge-oidc-secret
        # pvc:
        #   - name: deluge-config
        #     localstorage: true
        #     backup: true
