apiVersion: v1
stringData:
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:7E6tTT5oW2qNTNRkQmNuH1YFtk0f1MOenvzkWgOKpxxUqjrfmylbyrdOf/cxA3m0Cfy5mlsabKuyqNAK0LlgxsDIdw9ZIdD4FKlFrQYylJefIbrMyLE=,iv:N/5OImCkUuLFyjHgq+I7tO5ZA874NpS0rMbdaoYJGys=,tag:WMHq/lKV2s/2EQBXlnYcyA==,type:str]
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:TI5I+Xg9S9AoyWA9yKPfASREiFxw5//zyuV11LHF5gN7VpXFnK9oevPVssHjTYoZCD/aSSN+zzW3fhuA9E0gFgNyu1i/nr/ky869qd/JukrCvf639mgKKQjevf2/xz1gxSqLsX0/ln3UL/bf03/+53wxTqAol5Gc6IBqftGT3qf7LGxqmK1cT7FXFQB/iWgZRYhQtaP4t8TXElxdBJObgG1cFrtsYHplmvBc+g0TTzYNyB+XtOmftpxFy/MCR6Fd6+Kxhe+v6xve1w88zpT7mvVlT7B7gqUIAg5c4Sg9FUd++fTuX3wCLMkJpC+3CtKQWfxJTAgpgazFL7DI374KswBnCvA7qiDNe9LdgyvlvtugraX46jQpvQqmxZiADzYGUVKHOvkeX0+2ZKdTsMXPYZF1LX4ppziL5p74wkGmWOVDXNT9y83JG7YKh4/dGBEObZJWVsHNvB07ph2n0DVs1EH7dDDSRuQJIaNqnl6MV6iS46npQwEHn2KzdGmqbXvOsq/pUpob01HuomvIuy+lIZZoTWcEsJmskVxQDZvLzEgoJICRopIleOD7uocaJgHd/AcML7JPqaX2zjAlCUprOYvKCnUZ85iOOPSAjhnyKRyD64YORlykbEQ5MHu4UqcQhkgs6lXncU2PsewCzgFRAlgLOgqOD38=,iv:p3IiGTjxhib7o80STXCj+gHyTL1JixzsL5KT+KLWbc8=,tag:sxz7qenBOXhMEitnW7pJiw==,type:str]
kind: Secret
metadata:
  name: paperless-secret
  namespace: docs
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaXNNN1R3S3UvS3NVc3dn
        ekZmUFVzRXZTTmZCdWxLdllqNnZFRnU4d1M0CnlZL2tndkYxcUJvN0dCYWlqMG9Q
        NlJKemVoZ09sQW03czV6WXNqeDRVSWcKLS0tIHVuREtsenIrVXc4ZHo2U1pSRlVF
        akhuWlJDUStFcFFXenJtOG1YamhlZlEKZjjwGK4JTT/PpJ5hyD5uPMBoGDw1Z6jA
        H4sHeRXVToggw1eCvm6tixj4A+lOCLSl1RSng3rjx5o6quCbBCQRVQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  lastmodified: "2026-08-11T13:55:18Z"
  mac: ENC[AES256_GCM,data:tOs4NkYVwFXFCmp4u6dncLCFXN6wMeVA5RrnMU8YUKEoOvQNLI91eZLGfsopgBT+PiTDP1+H0C50o38vzafUIDNRBkRAwdITgLJ7aakfGSGXuq9IJ9Xh8j/JG4g42ja5p6LPfRLhCJo/al0SVuYl4jkcqyupnF7y6XZP4ThrK1U=,iv:Cy+Z40/cyT9Ky+a7SYlXZHJPvtN3o2GCK1MCJzLidWU=,tag:kpf1XoDuQ/loj6LZpr+gew==,type:str]
  version: 3.13.3
