apiVersion: v1
stringData:
  SSH_KEY: ENC[AES256_GCM,data:0aQ495XSZ5F0hC+dxr+3l+z+Vj6iGkNxyb1Il3ApUgdlEKNJPUuyV3yvb8XbObrt8fSWBLEs1LS9Hkrq6pbDloZujuKXhpzxaVd7estZwYUBdgfOJ4KJFzdATcOuIWW2Wkfy1X259vBAc5z8E9xf0tfhVLpnQCi7eNR6cPTE3vIs8Kqsx4gI5eJ/spE0uDnwM3Xf3Smqgck8fwCX2og7QJr7HpSlhi/jz/30Vp71L+LvQGTdCN9tD4xOyNdYJR5woTsZAirOg/tKjAR6bKU2nJUbVBbN5WLJzbON5KMjLBBa9neROghtzXS1vQMXcAQ4aDVa35o47IM2Rgpqd/3+zVMsdus5BZR01AYmO2Xge5euhAKSKH41cdU7BQ07d21XfejNd3jUec437zbCrLYh/NEbQxtH9uBPPUjkmQ+/ThfQJ4AIPCSbD85P6QyL6BVzjLOr3lK3Rk1g7P0pCPtTElP5ncTB7PiRsF4z0m9YY/fH0GUzskpe5ynPxU5AD8/J97t9,iv:JIAEXRjRdWltQvTynNqqe8f35swaZvZCba6O8Epi3uw=,tag:ra33XFrE2Uvf83vUf6xrRg==,type:str]
  SSH_USER: ENC[AES256_GCM,data:532Hlw==,iv:wnsHje9OV5MU8dx26PtJMFYxT4uJB8FuTuRPV5u5ehc=,tag:sXIiTvxPD5h9LAmR+uhSGQ==,type:str]
kind: Secret
metadata:
  name: knock-up-stream-creds
  namespace: ingress
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXa1BGUTlnMUlEanBaYlFj
        TGlJZjErYU8rTEtwZktPUFVTY0djc0pDakd3CnBGcGYzeWwyNnVaK3MreEpMM0FJ
        NnlaWTNIRWwxdjl0d3NLbThldFZqQ1UKLS0tIDdyYUVJMnFHeWYxWVY2anhMT01P
        TUlxS05mN2pMTnRyRUdaY2pxUU0vQmcKshPEGLo1Z1WhJaCDZo+QGNIPHZG17IkH
        G43gYDMcIjXOPJ1bN9bIMAAOOOHuIfOgog/Zl/5eufKMa5ScIo3hLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T23:02:55Z"
  mac: ENC[AES256_GCM,data:+IM5SRkU4MbDBqVbuB27/HCBEpqeXSdfiYNul1FO+AciZnuOibB9XBdYycypGlp5ntLW6qKwglJPzCYXmCSzbqqNsMYoCTmAFuqK9UeB/nZ4dVlKRydZWWucTtaxMYRQ2IS70wQ29JKJX5zyiDh9ePSi6ISpZCuDol+/yWE23JE=,iv:kOxh4Tj8f6I04smJj7FXGCMqmGaFf9aH27kpLGTvzf0=,tag:92F1/u0VBTP3bAeui/Jc6A==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.12.2
---
apiVersion: v1
stringData:
  SSH_KEY: ENC[AES256_GCM,data:744ULxsWd4PzHpwhIfbc4DuFSUvVsO++1jE1HQs0HpcMXTNUJEUb37YFazUriaEl9naXcSF+CHZwNdZjNn6s3t/va6uGDmaBkBtJiU5yI9Obv3EiexHdcFsoAtFRkfJ0Fkt6U+34vKW+r37kqo2JRceI7qlwo4uPBzfttOVPW82wBjqSee0NQ3gl4BPqsCpb3YwcMc1Ks8rfnETn5xuEyN5Tpy+HQ/E3ZEXCwHYtTbX2XJTf5/7S8pH3s4vMS52cnWGMGADZJKYS7P7apLLuE/4Mk7731Bt7A7eYmqH1jsuuU34xWXfqIyev22XfEp+x/Ltn6dgzbQvBvdUZKWwS5j1qvHi8jOtXIHXgDLedomNvVZOfwQI5NsN3FhYX/cdzId0lTIdAu4gMzz/ucDBZdZst0SCV5hVB3lEMQsBALP593FrYF9SQbfi2h8sX6MVL/U1OJkNHsLEzs4FcBVmbQKD1xV/ch+QGPo9Kl238D9+oxvXaLk0Xfu1gAOqn18GebimB,iv:wzwJ1FNlJ70RoFWtXjKIUYraoYcJHWHZ+kxjeRvXNvM=,tag:jUmXYgE1tbhkvYZAHIzLJg==,type:str]
  SSH_USER: ENC[AES256_GCM,data:GSL04g==,iv:aJUW9G2VXzK3vWpjSMvgumShgRkYefpdP3pd39i6eNQ=,tag:unBgfwSJVHQ7r/MihhsTmA==,type:str]
kind: Secret
metadata:
  name: cloud-end-creds
  namespace: ingress
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXa1BGUTlnMUlEanBaYlFj
        TGlJZjErYU8rTEtwZktPUFVTY0djc0pDakd3CnBGcGYzeWwyNnVaK3MreEpMM0FJ
        NnlaWTNIRWwxdjl0d3NLbThldFZqQ1UKLS0tIDdyYUVJMnFHeWYxWVY2anhMT01P
        TUlxS05mN2pMTnRyRUdaY2pxUU0vQmcKshPEGLo1Z1WhJaCDZo+QGNIPHZG17IkH
        G43gYDMcIjXOPJ1bN9bIMAAOOOHuIfOgog/Zl/5eufKMa5ScIo3hLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T23:02:55Z"
  mac: ENC[AES256_GCM,data:+IM5SRkU4MbDBqVbuB27/HCBEpqeXSdfiYNul1FO+AciZnuOibB9XBdYycypGlp5ntLW6qKwglJPzCYXmCSzbqqNsMYoCTmAFuqK9UeB/nZ4dVlKRydZWWucTtaxMYRQ2IS70wQ29JKJX5zyiDh9ePSi6ISpZCuDol+/yWE23JE=,iv:kOxh4Tj8f6I04smJj7FXGCMqmGaFf9aH27kpLGTvzf0=,tag:92F1/u0VBTP3bAeui/Jc6A==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.12.2
