---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-pg
  namespace: immich
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: postgres-oci
    namespace: flux-system
  values:
    image:
      registry: docker.io
      repository: tensorchord/vchord-postgres
      tag: pg18-v1.1.1

    customUser:
      name: immich

    podAnnotations:
      k8up.io/backupcommand: sh -c 'PGDATABASE="$CUSTOM_DB" PGUSER="$CUSTOM_USER" PGPASSWORD="$CUSTOM_PASSWORD" pg_dump --clean'
      k8up.io/file-extension: .sql

    persistence:
      storageClass: local-path
      size: 20Gi
      annotations:
        k8up.io/backup: "false"
    
    config: 
      postgresql:
        shared_preload_libraries: vchord.so

    initdb:
      scripts:
        load_extensions.sql: |-
          CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
          CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
