---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-logs-single
  namespace: victoriametrics
spec:
  interval: 1h
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-single
  ref:
    tag: 0.12.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: victoriametrics
  name: victoria-logs
spec:
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: victoria-logs-single
    namespace: victoriametrics
  values:
    server:
      image:
        repository: victoriametrics/victoria-logs
        tag: v1.50.0
      persistentVolume:
        annotations: 
          k8up.io/backup: "false"
        storageClassName: local-path
        size: 30Gi
      ingress:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - name: vmlogs.egghead.infrao.top
            path:
              - /
            port: http
        tls:
          - hosts:
            - vmlogs.egghead.infrao.top
    dashboards:
      enabled: true
