###
###
##### Files
###
###
---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: backup-services-files
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    repoPasswordSecretRef:
      name: garage-creds
      key: restic-password
    s3:
      endpoint: https://ohara.infrao.top:3900
      bucket: services-backup/services/
      accessKeyIDSecretRef:
        name: garage-creds
        key: ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: garage-creds
        key: ACCESS_SECRET_KEY
  backup:
    promURL: http://victoria-metrics-victoria-metrics-single-server.victoriametrics:8428
    schedule: '0 2 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
    podSecurityContext: # For pocket-id keys files
      runAsUser: 1000
      runAsNonRoot: true
  check:
    schedule: '0 2 * * 1'
  prune:
    schedule: '0 2 * * 0'
    retention:
      keepLast: 5
      keepDaily: 2