---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bentopdf
spec:
  interval: 10m
  chart:
    spec:
      chart: ./k8s/appchart
      version: "x.x.x"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: bentopdf
        image: ghcr.io/alam00000/bentopdf-simple:2.7.0
        podSpec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            runAsGroup: 101
            fsGroup: 101
        containerSpec:
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
        volumeMounts:
          - name: nginx-tmp
            mountPath: /etc/nginx/tmp
          - name: nginx-tmp2
            mountPath: /var/lib/nginx/tmp
          - name: nginx-cache
            mountPath: /var/cache/nginx
          - name: nginx-run
            mountPath: /var/run
        volumes:
          - name: nginx-tmp
            emptyDir: {}
          - name: nginx-tmp2
            emptyDir: {}
          - name: nginx-cache
            emptyDir: {}
          - name: nginx-run
            emptyDir: {}
        service: 8080
        ingress:
          domain: pdf.egghead.infrao.top
