# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: grist-creds
stringData:
  GRIST_SESSION_SECRET: ENC[AES256_GCM,data:F0R956Y2OSOrLSbUYTZUuRuMbLnPfggzuhT4Qa6babk=,iv:d30MgSPcY2uHQrOB9hDjdw6/Pye2FLFnQf8eh1olL4g=,tag:mDGpHMB7KenkachEyCeKIw==,type:str]
  GRIST_DEFAULT_EMAIL: ENC[AES256_GCM,data:m5ox8XuSvnfgkq4naTeT+PRd/+cLNVU=,iv:VgvT5QQfKRWukh5/70dVLco1KC++TgcyTbaRqzdZQnc=,tag:/FqXUaaLOvyKtZatyFyZag==,type:str]
  GRIST_OIDC_IDP_CLIENT_ID: ENC[AES256_GCM,data:+J6bbJGmTi+4q9dP5yw/rRBtHo5uyT/ibsbD0daI03NOxElb,iv:NPNVWmg7KVJwkr5MjUDc9t21Zs1lzpl76pXsD1kWr/4=,tag:DP1J0vnVfsSbEaARB5Of7A==,type:str]
  GRIST_OIDC_IDP_CLIENT_SECRET: ENC[AES256_GCM,data:CFCjPQPivb0KnEMm49dUtKFxgpg5QReb2m0NScBurWA=,iv:mIiLVM0VDQ51u/al2FYBlcMjsM5GR/ihbdDCOgIypuk=,tag:EZc+DxUtiAcbbHeVcGrmAw==,type:str]
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5U09tKzYxYjVoOW9YTE1J
        SDNWVXUxcmNsMktuUFp0dWswVndPeGw0WEdRCi92d3dGaEszOS9sNlpvSHlSaTJu
        bXdxRm1PVExMM2JYNVpMK2U1MEpmRncKLS0tIDJaZkNCWUJNazRQVEVkanVIWUsr
        WGxXVVZvSUdhNGJHdlo4QTJlYkkzM0UKH/u0FhIEQTvngNlv+R3uQtcTbW5JI1So
        GvmY9TS40+GIFyoKAJXJh02DstyUy/wZkzpP9p731VBWSQz4yjplQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T19:32:25Z"
  mac: ENC[AES256_GCM,data:pRfgXVP/HWyo27eVQhhWYSfTfAJjAsrNfJXvUs+Xuvux70pHm2FZ3+H/0trXXk/SKj2Hq/LS3fngKBKhC407EOHxo4MI3Rntqp6lzFIl4CdQaj999DcYlRpvwEP4cLfXoyGAPFX6PUnv+3OpVJkZ9BK8JcJd1SOemSBbc5FNCVI=,iv:w/Z6nHEgQkfwJcMWqbClTCUlFHA3XS5NPYC9WHMQ6Fg=,tag:q3D60bn/I1WS909Oz2EOlg==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.12.2
