apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:0dg3ah1Je5fITrh/S+jPk8+4qzrHyPaU6nwDPATbEdV4WCNKJ26fKYQ4G3IlzxaO3Bd1Z6FogFdWtgelNBojf7VOaPAB5FChC8mp0ekYpMUW5Kk1tOH9KZa6wCGP,iv:hcZdbhYqmkG6IpEzxl6Rsl6CZI5916B/MhODlqXR5iU=,tag:NYoU3BS+8k/GO6O2q7PlwA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eHZrNUJuYkdpSnFDVFhi
        V2NpK01TTmYzMXp5L0Q5QitqbEU3VVZwUEFBClc0ZXZxbk8rU3NLdVNlQXZZWmov
        bUxha3dScnl6S01sVEdIQ0FsZ1k2dTAKLS0tIGYzNXlOUmlwcU5SbkYvNDNnVXY2
        MktIMUt5RmNaaDEvT09oc0FVYmlXZ28K0Ry/pby3D2MbLLq4s6ZJ64WoNaTES9bA
        Nxpcp/3nJIG4yw00T9MsovpfGe9YKPo9KJPvtpeOHTSW5e/qHIbFdA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  lastmodified: "2026-07-03T15:07:48Z"
  mac: ENC[AES256_GCM,data:ppI0uQgpJOZE1wVnPc8UQzQkJVyNlC35skIM1cCcPUCeG0YFekeNVn1M++hdpopOsCIXgLU/9sCzIBvVIFMC1RFukOrFUlT6GAVjtjE93u7O0K0hk9kkTE10rCGca7OLzPYRZIPLEdEd2u6mIFqGQfUd+hnB+oEiWcYlumfGKjI=,iv:rQzpbh3Lh9ui0J68nyKRq8c107OHSE9dbatj7mLkpQA=,tag:vA+RJTYEw+EDv+TpA2faSw==,type:str]
  version: 3.13.1
