apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:F7mNNTmrmCkgHEga+Fzw+hA6NVPR/R2IfnSIYtT11EiwaXBw1KoZriRFkrjXAbdQRybEyLWBQxmvUgWi9QbeNF2E8+AjJEA28oTaue0PcwfLeVcsiMdquQ4MgAaq,iv:V30t/G8l50HjJa/iF1wBazohS2y7oz9UX5KbyuHmzSo=,tag:t530kkUlfXxnUqCLF/4k9Q==,type:str]
sops:
  age:
    - recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQlg4cDQ0bVVYNTRTSFZk
        R3ZDRW1QSzVDaXRmTUQwcjJBRXM0dEtpY0VzCjVSZVM5QnZ0N096T1VDa2JRRnh4
        MVVoR2NHRVlhZlZzQ2N2K21VOExiZGsKLS0tIGswN1E3S2ZrZEVNVnJ2eFlRdVkx
        M1hjYi9UY2REcXh4N1lsZkZwZ05CSFkKkaG+dC7v75WL0oLdsY04KJROm1GluSAc
        lyzI9E9W2jkNz/niYsXlPNxKcjUwrLOFJqDjSp8qRXUX+qna+Mz6Ug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-10T13:45:33Z"
  mac: ENC[AES256_GCM,data:SeJWqjjjdL/s+QiJZw4gzBYP7r0DBIBng4MiH7oPnq21qAJ3P1bcIgMQHmvOG2LsapPatk7Vaqqhz88dDOL+RJoh6MOA5x/K5RtKz/jGnmEaEwFGN0JeGjsfLFpuBwkpI4qi+r/cuRSdhZpgCfktg9lixNBdCRBG0jbivU+7QXc=,iv:/I23kKBm/yBN0A62Jsa3l29uq8X9ByAX1uLnYChJ150=,tag:y9Va8S2Jqfi2Pu5+wr+Lwg==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.12.2
