apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
type: Opaque
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:uE/846GA0RJXYWTU39vRIf7DXIOmPv6JVG4Q/KsE5P6K0W+4Sn3lCaMA5YJGYcJqLXGvGzYcTlgWiol95lwsZ0E+NDcxJbdFPSut6BIYdR3nF4aH7mOplscrYWXi,iv:8q/q0aTDWnQkJWL4K07ZetIs494KDqROenoNdBLB5y0=,tag:9snmz17hZRNoJs7VLzzi/A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eHZrNUJuYkdpSnFDVFhi
        V2NpK01TTmYzMXp5L0Q5QitqbEU3VVZwUEFBClc0ZXZxbk8rU3NLdVNlQXZZWmov
        bUxha3dScnl6S01sVEdIQ0FsZ1k2dTAKLS0tIGYzNXlOUmlwcU5SbkYvNDNnVXY2
        MktIMUt5RmNaaDEvT09oc0FVYmlXZ28K0Ry/pby3D2MbLLq4s6ZJ64WoNaTES9bA
        Nxpcp/3nJIG4yw00T9MsovpfGe9YKPo9KJPvtpeOHTSW5e/qHIbFdA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hqtagr9n8pg56xdzdp53ux5rucge4cpe9sh9t55zst6ruque4ftsw6papx
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  lastmodified: "2026-09-28T20:23:18Z"
  mac: ENC[AES256_GCM,data:HFSR69TzcURnZk3oBK5y486BkmzwlWjQCFGcxZt0NZkxibKSjb04FTy6JAl0M34Qi2j4qyISmBPwjoDNZN1t1tqcYIMADVlrMxz0m5EeaEKnkb7Fpo5zPCyPBBn56KtxPSIUlp7Jou8D5AKngNdzDq2UEl6BZJIrKbyAEoafArA=,iv:0hHKDO7mLRVaupxf9whuRoHLct+Z304MYx3qC3rBtGk=,tag:j6dklpkyzdp/AwJpzPcGtQ==,type:str]
  version: 3.13.3
