---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: romm-database
  namespace: services
  annotations:
    k8up.io/backup: "false"
spec:
  instances: 1
  imagePullPolicy: IfNotPresent
  storage:
    storageClass: nfs
    size: 1Gi
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6
  bootstrap:
    recovery:
      source: source
      recoveryTarget:
        backupID: "20260416T004500"
  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: garage-romm-backup-store
          serverName: romm-database-restore
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: garage-romm-backup-store
