---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: romm-pg
  namespace: services
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: postgres-oci
    namespace: flux-system
  values:
    image:
      registry: docker.io
      repository: postgres
      tag: "18.3"

    customUser:
      name: romm

    podAnnotations:
      k8up.io/backupcommand: sh -c 'PGDATABASE="$CUSTOM_DB" PGUSER="$CUSTOM_USER" PGPASSWORD="$CUSTOM_PASSWORD" pg_dump --clean'
      k8up.io/file-extension: .sql

    persistence:
      storageClass: local-path
      size: 5Gi
      annotations:
        k8up.io/backup: "false"
